name: yiapp
description: A new Flutter project.

version: 1.1.1

environment:
  sdk: ">=2.10.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  # 网络请求
  dio: ^3.0.9
  # 事件管理
  event_bus: ^1.1.1
  # 上传文件到七牛云
  flutter_qiniu: ^0.1.3
  # 生成 uuid
  uuid: ^2.2.0
  # 简单数据持久化存储
  #  shared_preferences: ^0.5.8
  shared_preferences: 0.5.7+2
  #---sql-lite------------
  sqflite: 1.1.8

  # 获取系统权限
  permission_handler: ^5.0.1+1
  # 从浏览器中打开一个url
  url_launcher: ^5.4.7
  # 下拉刷新、上拉加载
  flutter_easyrefresh: ^2.1.7
  # a___for model json
  json_annotation: ^3.0.1
  #
  web_socket_channel: ^1.1.0
  #  WeChat login
  # fluwx: ^2.3.0 kotlin 一直编译不通过，先注释该插件 8月20日

  ###### suxing #####
  # 图片缓存
  cached_network_image: ^2.2.0+1
  # 调用摄像机或相册
  image_picker: ^0.6.7+4
  # 可以一次选择多张图片
  multi_image_picker: ^4.7.14
  # 仿微信选择图片
  wechat_assets_picker: ^4.1.0+4
  # 多张图片的左右滑动
  photo_view: ^0.10.0
  # 状态管理
  provider: ^4.3.1
  # 第三方icon库
  font_awesome_flutter: ^8.8.1
  # 轮播图
  flutter_swiper: ^1.1.6
  # 公历黄历吉凶星座
  secret: ^0.1.1
  # 按钮、文字抖动的效果(摇签)
  shake_animation_widget: ^1.0.1
  # 左滑工具栏
  left_scroll_actions: ^1.5.3
  # 上拉加载、下拉刷新
  pull_to_refresh: ^1.6.2
  # 加载指示器
  flutter_spinkit: ^4.1.2
  # 简单的 loading 加载框
  flutter_easyloading: ^2.1.1
  # html 插件(用户协议)
  flutter_html: ^1.0.0
  # flutter 小部件UI库
  flui: ^0.9.2
  # flutter 屏幕适配
  flutter_screenutil: ^4.0.2
  # 获取app名称，版本号等
  package_info: ^0.4.3+2
  # 更新app弹框
  flutter_update_dialog: ^1.0.0
  ###### suxing #####
  flutter_svg: 0.18.0
  #----- mobile push service-------
  mobpush_plugin: ^1.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/iconfont.ttf
    - assets/images/avatar.jpg
    - assets/images/b.png
    - assets/images/bei_mian.png
    - assets/images/bg.jpg
    - assets/images/bg_blue.png
    - assets/images/boy.png
    - assets/images/fan.png
    - assets/images/girl.png
    - assets/images/girl_master.png
    - assets/images/god_of_wealth.png
    - assets/images/icon_selected_20x20.png
    - assets/images/ji.png
    - assets/images/l.png
    - assets/images/loop/loop_1.jpg
    - assets/images/loop/loop_2.png
    - assets/images/loop/loop_3.jpg
    - assets/images/loop/loop_4.jpg
    - assets/images/master.png
    - assets/images/plate.png
    - assets/images/plate_bg.png
    - assets/images/qian.png
    - assets/images/s.png
    - assets/images/shake_sign.png
    - assets/images/shopping_cart.png
    - assets/images/tai_chi.png
    - assets/images/temp_bg.png
    - assets/images/temp_boy.jpg
    - assets/images/temp_girl.jpg
    - assets/images/temp_wrong.jpg
    - assets/images/tlp.png
    - assets/images/w.png
    - assets/images/woman.png
    - assets/images/yi.png
    - assets/images/z.png
    - assets/images/zi_mian.png
    - assets/images/zodiac_plate.png
    - assets/images/bg_update_top.png
    - assets/update_ic_close.png
    - assets/images/ic_launcher.png
  fonts:
    - family: AliIcon
      fonts:
        - asset: assets/icons/iconfont.ttf
