name: yiapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  # 网络请求
  dio: ^3.0.9
  # 事件管理
  event_bus: ^1.1.1
  # 上传文件到七牛云
  flutter_qiniu: ^0.1.3
  # 生成 uuid
  uuid: ^2.2.0
  # 权限管理
  permission_handler: ^5.0.1+1

  ###### suxing #####
  # 图片缓存
  cached_network_image: ^2.2.0+1
  # 仿微信选择图片
  wechat_assets_picker: ^4.1.0+4
  # 状态管理
  provider: ^4.3.1
  ###### suxing #####

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

  fonts:
    - family: AliIcon
      fonts:
        - asset: assets/icons/iconfont.ttf